#!/usr/bin/env python
# -*- coding: utf-8 -*-

#+---------------------------------------------------------------------------+
#|          01001110 01100101 01110100 01111010 01101111 01100010            |
#|                                                                           |
#|               Netzob : Inferring communication protocols                  |
#+---------------------------------------------------------------------------+
#| Copyright (C) 2011 Georges Bossert and Frédéric Guihéry                   |
#| This program is free software: you can redistribute it and/or modify      |
#| it under the terms of the GNU General Public License as published by      |
#| the Free Software Foundation, either version 3 of the License, or         |
#| (at your option) any later version.                                       |
#|                                                                           |
#| This program is distributed in the hope that it will be useful,           |
#| but WITHOUT ANY WARRANTY; without even the implied warranty of            |
#| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              |
#| GNU General Public License for more details.                              |
#|                                                                           |
#| You should have received a copy of the GNU General Public License         |
#| along with this program. If not, see <http://www.gnu.org/licenses/>.      |
#+---------------------------------------------------------------------------+
#| @url      : http://www.netzob.org                                         |
#| @contact  : contact@netzob.org                                            |
#| @sponsors : Amossys, http://www.amossys.fr                                |
#|             Supélec, http://www.rennes.supelec.fr/ren/rd/cidre/           |
#+---------------------------------------------------------------------------+ 

#+---------------------------------------------------------------------------+
#| Standard library imports
#+---------------------------------------------------------------------------+
import sys
import logging.config
import gobject
import os
import optparse

#+---------------------------------------------------------------------------+
#| Prepare, load and import the required modules
#+---------------------------------------------------------------------------+
sys.path.insert(0, 'src/')

# Insert in the path the directory where _libNeedleman.pyd is
if os.name == 'nt':
    sys.path.insert(0, 'lib/libNeedleman/')

try:
    # Verify that libNeedleman is in the path
    import _libNeedleman
except:
    # Else, assume the path is gotten from the 'python setup.py build' command
    arch = os.uname()[-1]
    python_version = sys.version[:3]
    build_lib_path = "build/lib.linux-" + arch + "-" + python_version
    sys.path.append(build_lib_path)

import netzob.NetzobGui as NetzobGui
from netzob import release




if __name__ == "__main__":
    gobject.threads_init() # for handling concurrent GUI access from threads

    
    netzob = NetzobGui.NetzobGui()
    netzob.startGui()
